### ISSUE TITLE
Some latency data not displayed in chart after 3.5.1 upgrade

### ISSUE THREAD

**Issue by apertome** [perfsonar/graphs#33] opened 2016-03-09 22:11 UTC
We have a report that some latency data is missing from the charts. Specifically, at the one day zoom level (so, using statistics with a summary window of 0). Here are the details:

After an upgrade to v3.5-1, the chart that shows measured data seems to have a display issue. To be more specific, the chart does not display all available ‘Latency’ data it has *when zoomed to 1 day* by mouse *click* on ‘1d’ above the chart (not by window dragging, which is below the chart).

For example, the following links show charts that display measurement data between two nodes (128.112.228.24 and 128.112.228.23). The query was made on March 9, 2016, at around *2:54 pm*.  However, when zoomed to *1 day*, the display cuts off at around 7:33 am. When zoomed to *3 day*, the data is displayed up to roughly 2:54pm. 

In other words, zooming to *1d* seems to cut off displayed latency data, even though the data *is* actually there.  Note that ‘Ping’ data is not cut off. 

Zoom: 1 day (1d)
https://perfsonar-ma-2.princeton.edu/perfsonar-graphs/graphWidget.cgi?url=https://perfsonar-ma-2.princeton.edu/esmond/perfsonar/archive&source=perfsonar-hpcrc-delay.princeton.edu&dest=perfsonar-87prospect-delay.princeton.edu#timeframe=1d

Zoom: 3 day (3d)
https://perfsonar-ma-2.princeton.edu/perfsonar-graphs/graphWidget.cgi?url=https://perfsonar-ma-2.princeton.edu/esmond/perfsonar/archive&source=perfsonar-hpcrc-delay.princeton.edu&dest=perfsonar-87prospect-delay.princeton.edu#timeframe=3d

* Zoomed to between 6am - 2:54pm by dragging the window with mouse, so that the difference between 1d and 3d is more obvious (i.e., 1d zoom is missing latency data)

Zoom: 1 day
https://perfsonar-ma-2.princeton.edu/perfsonar-graphs/graphWidget.cgi?url=https://perfsonar-ma-2.princeton.edu/esmond/perfsonar/archive&source=perfsonar-hpcrc-delay.princeton.edu&dest=perfsonar-87prospect-delay.princeton.edu#timeframe=1d&zoom_start=1457520917158&zoom_end=1457553245000

Zoom: 3 day
https://perfsonar-ma-2.princeton.edu/perfsonar-graphs/graphWidget.cgi?url=https://perfsonar-ma-2.princeton.edu/esmond/perfsonar/archive&source=perfsonar-hpcrc-delay.princeton.edu&dest=perfsonar-87prospect-delay.princeton.edu#timeframe=3d&zoom_start=1457520917158&zoom_end=1457553245000

**Comment by arlake228** [comment] 2016-03-14 20:28
Turns out this was caused by changes to esmond. The default limit for the number of results returned was set to 1000 thus only the first 1000 results were displaying. Additional results are paginated but the perl client does not know how to follow the pagination headers currently. When you are looking at 24 hours of 1 minute latency data summaries, you'll have 1440 points. Thus the last 440 points were cut-off in the one day view. This was fixed in the near-term by bumping the default limit in esmond to 1500. A more general issue was created in perfsonar/perl-shared#12 to actually update the perl client to follow pagination headers so the limit is irrelevant in cases like this. In the meantime, another workaround one could do is to pass the limit= option in the GET parameters and set it to a higher number.

**Closed by arlake228** 2016-03-14 20:28 UTC
Labels: bug
