### ISSUE TITLE
Deterministic selection of "source" and "destination"

### ISSUE THREAD

**Issue by candlerb** [perfsonar/graphs#25] opened 2015-09-20 18:06 UTC
Usability problem:

* In the psGraph.cgi listing, it seems to be arbitrary which way round is "source" and "destination"
* As a result, in the graphs you generate by clicking on this, it is arbitrary which is the solid line, and which is the dotted line ("reverse", meaning "destination to source")

This makes a quick interpretation of the graphs difficult, as you always have to double-check which way round source and destination are.

However the esmond meadata does store the "measurement agent" which I think means the side which initiated the test.

Hence the tools which read the data could swap "source" and "dest" if dest == measurement agent?

**Comment by apertome** [comment] 2015-09-28 14:32
This is a duplicate of #9, but I'm leaving this open and closing that ticket, as this explains it a bit better. I also like the suggestion of using the "measurement-agent" to determine which node is the source.

Other solutions we've discussed:
Detect the local addresses (we already have code that does this part). Then, anything that is on the local machine should be considered the "source"

If nothing else, it would be good to at least remember which addresses it has listed as source and remain consistent in how it displays them.

**Comment by apertome** [comment] 2016-02-15 22:08
cc80838936389d1e01a5bb15d050058602c496d6 also updates this.

**Comment by apertome** [comment] 2016-02-15 22:12
Based on discussions on the dev meetings, we determined that at the Toolkit level, we should treat the the local host as the "source" when possible. The code now checks to see whether the IP address of a test member matches those on the local host. If so, it ensures that that is the "source." Also, the interface now sorts the tests by source, then destination, for additional consistency and readability.

**Closed by apertome** 2016-02-15 22:12 UTC
Labels: bug
