### ISSUE TITLE
FEAT: "today" button and time travels

### ISSUE THREAD

**Issue by igarny** [perfsonar/graphs#45] opened 2016-10-18 09:41 UTC
Hi Michael,

In fact here are 2 feature request. Tightly related to one other.
1) First is simply to have a button today. My suggestion is to function as a fast forwarder to the current date and time, but preserving the selected duration interval.

2) My call is to stop shifting the time range to include the current date/time with period selection dialog, but to just adjust the time period according to the selected point in time.

3) When changing the visualization period in graphs I would suggest, that the implementation of 2) always uses the end point in time of the "old" selection. I suggest this approach in order to preserve consistency with the "today" button.

Regards,
Ivan

**Comment by apertome** [comment] 2016-10-28 20:00
Ivan, 2/3 are already done and will be in 4.0 RC2.

#1 is a duplicate of #42  so I'm closing this ticket.

**Closed by apertome** 2016-10-28 20:00 UTC
Labels: enhancement
